apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: curlimages/curl:7.72.0
          command: ["/bin/sh", "-c", "--"]
          args: [
            "sleep 10; while true; do curl -s http://k8s-ingress-external-6a7a6af6f3-ae601dc34620e51b.elb.ap-southeast-1.amazonaws.com/; sleep 1 && echo ''; done"
          ]
          # args:
          #   - >
          #     sleep 10;
          #     while true; do
          #       echo -n "$(date): ";
          #       curl -s http://backend.local/;
          #       echo '';
          #       sleep 1;
          #     done
---
# ConfigMap for backend stable
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-v1
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 80;
        location / {
          return 200 '{"name":"backend","version":"1"}';
        }
      }
    }

---
# ConfigMap for backend canary
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-v2
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 80;
        location / {
          return 200 '{"name":"backend","version":"2"}';
        }
      }
    }

---
# Stable Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-stable
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
      version: "1"
  template:
    metadata:
      labels:
        app: backend
        version: "1"
    spec:
      containers:
        - name: backend-v1
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx
              name: nginx-config
      volumes:
        - name: nginx-config
          configMap:
            name: backend-v1

---
# Canary Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      version: "2"
  template:
    metadata:
      labels:
        app: backend
        version: "2"
    spec:
      containers:
        - name: backend-v2
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx
              name: nginx-config
      volumes:
        - name: nginx-config
          configMap:
            name: backend-v2

---
# Service for stable
apiVersion: v1
kind: Service
metadata:
  name: backend-service-stable
spec:
  selector:
    app: backend
    version: "1"
  ports:
    - port: 80
      targetPort: 80

---
# Service for canary
apiVersion: v1
kind: Service
metadata:
  name: backend-service-canary
spec:
  selector:
    app: backend
    version: "2"
  ports:
    - port: 80
      targetPort: 80

---
# Ingress for stable
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress-stable
  annotations:
    kubernetes.io/ingress.class: external-nginx
    # nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: external-nginx
  rules:
    - host: k8s-ingress-external-6a7a6af6f3-ae601dc34620e51b.elb.ap-southeast-1.amazonaws.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-service-stable
                port:
                  number: 80

---
# Ingress for canary (10%)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress-canary
  annotations:
    kubernetes.io/ingress.class: external-nginx
    # nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "20"
spec:
  ingressClassName: external-nginx
  rules:
    - host: k8s-ingress-external-6a7a6af6f3-ae601dc34620e51b.elb.ap-southeast-1.amazonaws.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-service-canary
                port:
                  number: 80
